# Generated by Django 5.1 on 2024-08-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_batch_faculty_semester_student_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semesters',
            field=models.ManyToManyField(related_name='students', to='examination.semester'),
        ),
    ]
