# Generated by Django 5.1 on 2024-08-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_student_semesters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
