# Generated by Django 5.1 on 2024-08-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_rename_lname_student_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
